people = {
    "Cristiano Ronaldo": 668,
    "Lionel Messi":	510,
    "Selena Gomez":	416,
    "Kylie Jenner":	391,
    "Dwayne Johnson": 391,
    "Ariana Grande": 373,
    "Kim Kardashian": 354,
    "Beyoncé": 308,
    "Khloé Kardashian":	300,
    "Nike":	298,
    "Justin Bieber": 292,
    "Kendall Jenner": 285,
    "Taylor Swift":	281,
    "National Geographic": 276,
    "Virat Kohli": 274,
    "Jennifer Lopez": 247,
    "Neymar": 231,
    "Kourtney Kardashian": 216,
    "Miley Cyrus": 211,
    "Katy Perry": 202,
    "Real Madrid": 180,
    "Zendaya": 176,
    "Kevin Hart": 176,
    "Cardi B": 163,
    "LeBron James": 158,
    "Demi Lovato": 152,
    "Rihanna": 149,
    "FC Barcelona": 145,
    "Chris Brown": 144,
    "Drake": 142,
    "Ellen DeGeneres": 134,
    "Kylian Mbappé": 128,
    "Billie Eilish": 124,
    "UEFA Champions League": 121,
    "Lisa Manobal": 106,
    "Gal Gadot": 106,
    "Vin Diesel": 104,
    "Narendra Modi": 99.2,
    "NASA": 97.2,
    "Shraddha Kapoor": 94.9,
    "Shakira": 94.3,
    "Priyanka Chopra": 93.6,
    "NBA": 90.4,
    "Dua Lipa": 88.7,
    "Snoop Dogg": 88.6,
    "Jennie": 88.5,
    "David Beckham": 88.4,
    "Alia Bhatt": 86.6,
    "Rosé": 84.3,
}

descriptions = {
    "Cristiano Ronaldo": "Footballer",
    "Lionel Messi":	"Footballer",
    "Selena Gomez":	"Musician and actress",
    "Kylie Jenner":	"Media personality",
    "Dwayne Johnson": "Actor and professional wrestler",
    "Ariana Grande": "Musician and actress",
    "Kim Kardashian": "Media personality",
    "Beyoncé": "Musician and actress",
    "Khloé Kardashian":	"Media personality",
    "Nike":	"Sportswear multinational",
    "Justin Bieber": "Musician",
    "Kendall Jenner": "Media personality",
    "Taylor Swift":	"Musician",
    "National Geographic": "Magazine",
    "Virat Kohli": "Cricketer",
    "Jennifer Lopez": "Musician and actress",
    "Neymar": "Footballer",
    "Kourtney Kardashian": "Media personality",
    "Miley Cyrus": "Musician and actress",
    "Katy Perry": "Musician",
    "Real Madrid": "Football club",
    "Zendaya": "Actress and singer",
    "Kevin Hart": "Comedian and actor",
    "Cardi B": "Musician and actress",
    "LeBron James": "Basketball player",
    "Demi Lovato": "Musician and actress",
    "Rihanna": "Musician",
    "FC Barcelona": "Football club",
    "Chris Brown": "Musician",
    "Drake": "Musician",
    "Ellen DeGeneres": "Comedian and television host",
    "Kylian Mbappé": "Footballer",
    "Billie Eilish": "Musician",
    "UEFA Champions League": "Club football competition",
    "Lisa Manobal": "Musician",
    "Gal Gadot": "Actress",
    "Vin Diesel": "Actor",
    "Narendra Modi": "Prime Minister of India (2014–present)",
    "NASA": "Space agency",
    "Shraddha Kapoor": "Actress",
    "Shakira": "Musician",
    "Priyanka Chopra": "Actress",
    "NBA": "Basketball league",
    "Dua Lipa": "Musician",
    "Snoop Dogg": "Musician",
    "Jennie": "Musician",
    "David Beckham": "Footballer",
    "Alia Bhatt": "Actress",
    "Rosé": "Musician",
}

def GetFollowers(name):
    return people[name]

def GetDescription(name):
    return descriptions[name]